# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20170715_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
